version: "3"

services:
  backend:
    image: bram814/so1p2_node
    container_name: container_backend_node
    restart: always
    ports:
      - "5000:5000"

  frontend:
    image: bram814/so1p2_frontend
    container_name: container_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend